---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-msi-operator
  namespace: default
---
# Define Role that allows operations on K8s pods/deployments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-msi-operator
rules:
  - apiGroups: ["*"]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["aadpodidentity.k8s.io"]
    resources: ["azureidentities"]
    verbs: ["*"]
  - apiGroups: ["aadpodidentity.k8s.io"]
    resources: ["azureidentitybindings"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: azure-msi-operator
subjects:
  - kind: ServiceAccount
    name: azure-msi-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: azure-msi-operator
  apiGroup: rbac.authorization.k8s.io
